updated docker.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -31,13 +31,35 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
-    - name: SSH into EC2 and setup kubectl and minikube
+    - name: SSH into EC2 and setup Docker, Kubectl, Minikube and Deploy
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.EC2_HOST }}
         username: ubuntu
         key: ${{ secrets.EC2_KEY }}
         script : |
+          # Add user to the docker group if not already a member
+          sudo usermod -aG docker $USER
+          newgrp docker
+
+          # Check if Docker is installed
+          if ! [ -x "$(command -v docker)" ]; then
+            echo "Docker is not installed. Installing Docker..."
+            sudo apt update -y
+            sudo apt install docker.io -y
+            sudo systemctl enable docker
+          else
+            echo "Docker is already installed."
+          fi
+
+          # Verify Docker installation
+          if docker --version; then
+            echo "Docker installed successfully."
+          else
+            echo "Failed to install Docker."
+            exit 1
+          fi
+          
           # Install kubectl if not already installed
           if !kubectl version --client; then
             echo "kubectl is not installed. Installing now..."
@@ -64,13 +86,7 @@ jobs:
           else
             echo "kubectl already installed."
           fi
-    - name: Check if minikube is installed
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ubuntu
-        key: ${{ secrets.EC2_KEY }}
-        script : |
+          
           # Install minikube if not installed
           if ! minikube version; then
             echo "Minikube is not installed. Installing now..."
@@ -80,14 +96,7 @@ jobs:
             echo "Minikube is already installed."
           fi
 
-
-    - name: Check if minikube is running
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ubuntu
-        key: ${{ secrets.EC2_KEY }}  
-        script : |
+          # Check if minikube is running
           if ! minikube status --format '{{.Host}}' | grep "Running"; then
             echo "Minikube is not running. Starting minikube..."
             minikube start --nodes 2 -p test-cluster --driver=docker
@@ -96,13 +105,7 @@ jobs:
             echo "Minikube is already running."
           fi
 
-    - name: Verify Kubernetes Access
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ubuntu
-        key: ${{ secrets.EC2_KEY }}  
-        script: |
+          # Verify Kubernetes Access
           if kubectl get nodes; then
             echo "Kubernetes cluster is accessible."
           else
@@ -110,38 +113,20 @@ jobs:
             exit 1
           fi
 
-    - name: Get minikube cluster info
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ubuntu
-        key: ${{ secrets.EC2_KEY }}
-        script: |
+          # Get minikube cluster info
           if kubectl cluster-info; then
             echo "Cluster information fetched successfully."
           else
             echo "Cluster is not reachable."
           fi
 
-    - name: Fetch Latest Code using git checkout
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ubuntu
-        key: ${{ secrets.EC2_KEY }}
-        script: |
+          # Fetch Latest Code using git checkout
           echo "Checking out the git and Pulling the latest version"
           cd docker-compose-example
           git checkout main
           git pull -u origin main
 
-    - name: Deploy Backend to minikube
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ubuntu
-        key: ${{ secrets.EC2_KEY }}
-        script: |
+          # Deploy Backend to minikube
           cd docker-compose-example
           if kubectl get pods; then
             echo "Deploying to Minikube..."
@@ -151,13 +136,7 @@ jobs:
             exit 1
           fi
 
-    - name: Deploy Frontend to minikube
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ubuntu
-        key: ${{ secrets.EC2_KEY }}
-        script: |
+          # Deploy Frontend to minikube
           cd docker-compose-example
           if kubectl get pods; then
             echo "Deploying to Minikube..."
@@ -167,13 +146,7 @@ jobs:
             exit 1
           fi
 
-    - name: Verify Pods are running
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.EC2_HOST }}
-        username: ubuntu
-        key: ${{ secrets.EC2_KEY }}
-        script: |
+          # Verify Pods are running
           if kubectl get pods; then
             kubectl get pods -o wide
           else
